name: CI/CD Pipeline

# Déclencheurs (Triggers)
on:
  push:
    branches:
      - main
    tags:
      - 'v*' 

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest # Environnement demandé

    steps:
      # 1. Récupérer le code
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2. Installer Node.js version 22
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 3. Installer les dépendances
      - name: Installation des dépendances
        working-directory: ./backend
        run: npm install

      # 4. Lancer les tests
      - name: Lancement des tests
        working-directory: ./backend
        run: npm test

      # 4. Lancer les tests
      - name: Lancement des tests
        run: npm test

      # 5. Déploiement conditionnel (uniquement si c'est un tag)
      - name: Déploiement
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "Déploiement en cours..."